name: Deployment

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cloud Functions Deploy
        uses: google-github-actions/deploy-cloud-functions@v0.1.2
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          name: python-hello-world-cf
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          region: europe-west1
          source_dir: src
          entry_point: hello_world
          runtime: python39
          timeout: 120 # Increased timeout to 120 seconds
          max_instances: 1

