name: Deploy Cloud Function

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

      - name: Store GCP Service Account Key
        run: echo "${{ secrets.GCP_SA_KEY }}" > ${{ github.workspace }}/gcloud-service-key.json

      - name: Deploy Cloud Function
        run: |
          ssh -i ${{ secrets.GCP_SSH_PRIVATE_KEY }} prajesh@${{ secrets.VM_IP }} << 'EOF'
            # Authenticate with gcloud on the VM
            gcloud auth activate-service-account --key-file=gcloud-service-key.json

            # Configure gcloud
            gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
            gcloud config set functions/region asia-south1

            # Deploy the Cloud Function
            gcloud functions deploy python-hello-world-cf \
              --entry-point hello_world \
              --runtime python39 \
              --trigger-http \
              --allow-unauthenticated \
              --source src \ 
              --timeout 300s \
              --max-instances 1

            # Get the Cloud Function URL
            URL=$(gcloud functions describe python-hello-world-cf --format='value(httpsTrigger.url)')
            echo "Cloud Function deployed at: $URL"
          EOF


