name: Deployment

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: List src directory contents
        run: ls -la src

      - name: Cloud Functions Deploy
        uses: google-github-actions/deploy-cloud-functions@v0.1.2
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          name: python-hello-world-cf
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          region: asia-south1
          source_dir: src
          entry_point: hello_world
          runtime: python39
          timeout: 300
          max_instances: 1
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true

