name: Deploy Cloud Function

on:
  push:
    branches:
      - main  

permissions:
  contents: read  
  id-token: write 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/800832125481/locations/global/workloadIdentityPools/my-github-pool/providers/github'
          service_account: 'cloud-function-sa@prajesh.iam.gserviceaccount.com'
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: true
          access_token_lifetime: 3600s
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: prajesh

      - name: Configure gcloud
        run: |
          gcloud config set project prajesh
          gcloud config set functions/region asia-south1

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy python-hello-world-cf \
            --entry-point hello_world \
            --runtime python39 \
            --trigger-http \
            --allow-unauthenticated \
            --source src \
            --timeout 300s \
            --max-instances 1

      - name: Get Cloud Function URL
        run: |
          URL=$(gcloud functions describe python-hello-world-cf --format='value(httpsTrigger.url)')
          echo "Cloud Function deployed at: $URL"
